algoritmo "pgm08"
// Função :   Utilizar variaveis
// Autor : Willian Carlos Gomes
// Data : 20/01/2021
// Seção de Declarações Pratica em aula

var
Salario: real
Vale: real

inicio
// Atribuições e leitura de dados
Escreva ("Digite o seu salário:")
leia (Salario)
Escreval ("Digite o seu vale-refeição")
leia (Vale)

//exibir os dados digitados pelo usuário
Escreval ("Seu salário é:", Salario)
Escreval ("Seu vale-refeição é:", Vale)

fimalgoritmo
