algoritmo "pgm43"
// Função : Valor maior ou não que dez
// Autor :  Willian Carlos Gomes
// Data : 27/01/2021

// Seção de Declarações
var
valor: inteiro

inicio
//Leitura do valor
escreval("Digite o valor:")
leia(valor)

//Condicionais
se (valor>10) entao
   escreval("O valor informado é maior que dez.")
fimse

se (valor<=10) entao
   escreva ("O valor informado não é maior que dez.")
fimse


fimalgoritmo
