algoritmo "pgm05"
// Função : utilizar a variavel inteiro
// Autor :  Willian Carlos Gomes
// Data : 20/01/2021
// Seção de Declarações
var
Idade, Altura, Peso: inteiro

inicio
//Atribuição de valores às variáveis
idade <- 18
Altura <- 1,64
Peso <- 58

//Impressões em tela
Escreval     ("Qual a sua idade?")
Escreval     (idade)
Escreval     ("Qual a sua altura?")
Escreval     (Altura)
Escreval     ("Qual o seu peso?")
Escreval     (Peso)
fimalgoritmo
