algoritmo "pgm37"
// Função : Análise e codificação de algoritmos
// Autor : Willian Carlos Gomes
// Data : 25/01/2021

// Seção de Declarações 
var
A, B, C: inteiro

inicio
//Atribuições de valores às variáveis
A <- 30
B <- 20
C<- (A + B)

// Impressão dos valores em tela
escreval(C)
B <- 10

escreval(B, C)

//Alteração de variável
C <- (A + B)

// Impressão dos valores em tela
escreval(A, B, C)

fimalgoritmo
