algoritmo "pgm04"
// Função : Utilizar variaveis
// Autor : Willian Carlos Gomes
// Data : 20/01/2021

// Seção de Declarações
var
celular, cidade, nome: caractere

inicio
// Atribuição dos valores às variaveis
nome <- "Willian"
celular <- "(41) 9 9804-5682"
Cidade <- "Curitiba"

//impressões em tela
Escreval ("Qual o meu nome?")
Escreval (nome)

Escreval ("Qual o seu numero de celular?")
Escreval (celular)

Escreval ("Sua cidade?")
Escreval (cidade)

fimalgoritmo
