algoritmo "pgm11"
// Função : Multiplicação
// Autor : Willian Carlos Gomes
// Data : 21/01/2021

// Seção de Declarações
var
v1, v2, res: real

inicio
//Atribuições de valores às variáveis
escreval("Digite o valor da base (sem a unidade de medida):")
leia(v1)

escreval("Digite o valor da altura (sem a unidade de medida):")
leia(v2)

//Cálculo
res <- (v1 * v2)

// Impressão dos valores em tela
escreval("O resultado da área, na respectiva unidade de medida é:", res)

fimalgoritmo

