algoritmo "pgm44"
// Função : Verificar se o número é positivo ou negativo
// Autor :  Willian Carlos Gomes
// Data : 27/01/2021

// Seção de Declarações
var
valor: inteiro

inicio
//Leitura dos valores
escreval("Digite o valor:")
leia(valor)

//Condicionais e respectivas impressões
se (valor>=0) entao
   escreval("O valor informado é positivo.")
fimse

se (valor<0) entao
   escreva ("O valor informado é negativo.")
fimse
fimalgoritmo
