algoritmo "pgm48"
// Função : Verificar maior valor
// Autor :  Willian Carlos Gomes
// Data : 28/01/2021

// Seção de Declarações
var
v1, v2: inteiro

inicio

//leitura dos valores
escreval("Digite o primeiro valor:")
leia(v1)

escreval("Digite o segundo valor")
leia(v2)

//condicionais compostas
se (v1>v2) entao
   escreval("O primeiro valor é o maior.")
senao
   escreval("O segundo valor é o maior.")
fimse

fimalgoritmo
