algoritmo "pgm26"
// Função : Cálculo de dia e mês
// Autor :  Willian Carlos Gomes
// Data : 22/01/2021

// Seção de Declarações 
var
dia, mes, diasano: inteiro

inicio
//Leitura e atribuições das variáveis de dia e mês
escreval("Informe o dia:")
leia(dia)

escreval("Informe o mês")
leia(mes)

//Cálculo: Diminuí 1 mês pois o cálculo se refere ao mês correspondente
diasano <- ((mes*(30-1) + dia

//Impressão em tela
escreval("Se passaram ", diasano," desde o início do ano.")

fimalgoritmo
