algoritmo "pgm24"
// Função : Notas
// Autor :  Willian Carlos Gomes
// Data : 22/01/2021
// Seção de Declarações 
var
n1, n2, n3, media: real
inicio

//Atribuições às variáveis de notas
escreval("Digite a primeira nota:")
leia(n1)

escreval("Digite a segunda nota:")
leia(n2)

escreval("Digite a terceira nota:")
leia(n3)

//Cálculo da média
media <- (n1/2) + (n2/3) + (n3/5)

//Impressão em tela
escreval("A média final é: ",media)

fimalgoritmo
